POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
SRC += iqs5xx.c i2c_master.c trackpad_config.c
HAPTIC_ENABLE = yes
HAPTIC_DRIVER += drv2605l
GPKRC_ENABLE = yes
ENCODER_MAP_ENABLE = yes
COMBO_ENABLE = yes
